[package]
name = "glyphs-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
debug = true